#+TITLE: 西方经济学
#+STARTUP: indent
#+DATE: <2020-09-24 Thu>
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup

* 需求和供给

** 需求曲线与供给曲线

*** 需求

一种商品的需求指消费者在一定时期内，其他条件不变的条件下，在各种可能的
价格水平原意并且能够购买的该商品的数量

*** 需求量的变动与需求的变动

- 需求量变动：点动线不动，价格变动

- 需求变动：线动，非价格变动

*** 商品的分类分类

1. 普通商品：价格上涨，数量下降

2. 吉芬商品：价格上涨，数量上涨（爱尔兰土豆、中国房产）

3. 正常品：收入上涨，数量上涨

4. 低档品：收入上涨，数量下降

5. 替代品：相关商品价格上涨，数量上涨（猪肉牛肉）

6. 互补品：相关商品价格上涨，数量下降（停车费，汽车）

7. 不相关商品

*** 市场需求

单个需求的水平加总

*** 需求规律

- 特征，一般都向右下方倾斜
  
- 特殊情况

  1. 水平直线，单个厂商的需求曲线

  2. 向右上方倾斜的曲线，吉芬商品

*** 供给

 一定时期，其他条件不变，各个可能价格水平上厂商愿意并能够提供的商品数量

*** 供给量的变动与供给的变动

1. 供给量的变动是指由某商品的价格变动所引起的该商品供给数量的变动

2. 供给的变动是指由于非价格因素变动所引起的该商品供给数量的变动

*** 供给规律和特例

- 特征，一般都向右上方倾斜
  
- 特殊

  1. 向后方弯曲 （劳动供给曲线）

  2. 水平和竖直

** 均衡与比较静态分析

*** 均衡

当一个经济量在其他经济量相互作用下达到一种相对静止状态是，称该经济量处
于均衡状态

*** 均衡价格与均衡数量

一种商品的均衡价格是指该种商品的市场需求量和市场供给量相等时候的同一价
格。在均衡价格水平下的相等的供求数量被称为均衡数量。

*** 比较静态分析

分析在外生变量变化时引起的内生变量的变化。即外生变量发生变化以后经济现
象的均衡状态的相应变化，以及有关的经济变量在达到均衡状态时的相应变化。

** 弹性理论                                                       :2020重点:

*** 需求的价格弹性

$需求的价格弹性系数 = \frac{需求的变动率}{价格的变动率}$

$E = - \frac{\frac{\Delta Q}{Q}}{\frac{\Delta P}{P}} = - \frac{\Delta
Q}{\Delta P} \cdot \frac{P}{Q}$

**** 本质：

1. 变动速度之比

2. 数量变化对价格变化是否敏感
   
**** 分类：

1. $|E| > 1$ 富有弹性

2. $|E| = 1$ 单位弹性 反比例函数 $Q = \frac{K}{P}$

3. $|E| < 1$ 缺乏弹性

4. $|E| = +\infty$ 完全富有弹性

5. $|E| = 0$ 完全无弹性

**** 影响弹性的因素

1. 商品的可替代性，越多越大

2. 商品的用途的广泛性，越广泛越大

3. 商品多消费者生活的重要程度，越重要越小

4. 商品消费支出在消费者预算总支出中所占的比重，越小越小

5. 所考察的消费者调节需求量的时间，越短越小，例如香烟

**** 弹性概念的扩大

1. 需求的收入弹性 $e_I = \frac{\frac{\Delta Q}{Q}}{\frac{\Delta I}{I}}
   = \frac{\Delta Q}{\Delta I} \cdot \frac{I}{Q}$

   - $e_I > 0$ 正常品，需求量随收入水平增加而增加

   - $e_I < 0$ 劣等品，需求量随收入水平增加而减少

2. 恩格尔定律，对一个国价或者一个家庭而言，富裕程度越高，食物支出的收
   入弹性就越小

3. 需求的交叉弹性 $e_{XY} = \frac{\frac{\Delta Q_X}{Q_X}}{\frac{\Delta
   P_Y}{P_Y}} = \frac{\Delta Q_X}{\Delta P_Y} \cdot \frac{P_Y}{Q_X}$

   - $e_{XY} > 0$ 替代品

   - $e_{XY} < 0$ 互补品

   - $e_{XY} = 0$ 不相关商品

**** 供给弹性

*看曲线与X轴（Q）的截距*

- 小于0则弹性大于1

- 过原点则弹性等于1

- 大于0则弹性小于1

**** 供给弹性的应用

1. 限价

   1. 支持价格（最低限价），$P_c > P_E$，过剩经济，保护生产者（粮食最
      低收购价）

   2. 限制价格（最高限价），$P_f < P_E$，短缺经济，保护消费者（限价房）

2. 税收的分担

   税收负担更多地落在缺乏弹性的市场一方身上，若某一方完全缺乏弹性，则
   税收完全由它承担

   $\frac{消费者承担部分}{厂商承担部分} = \frac{供给弹性}{需求弹性}$

* 效用论

效用论的核心作用是从理论上推导需求曲线

** 基本概念

*** 效用

消费者在消费商品时所感受的满足程度（主观感受）

*** 效用理论分类

1. 基数效用理论

   - 效用可以具体衡量

   - 效用可以加总求和

   - 具体效用量之间可以比较

   - 分析方法：边际效用递减规律

2. 序数效用理论

   - 效用不可度量

   - 效用不可加总

   - 效用可以比较排序

   - 分析方法：无差异曲线

** 基数效用理论

1. 总效用 $TU = f(Q)$

2. 边际效用 $MU = \frac{\Delta TU(Q)}{\Delta Q}$

3. 边界效用递减规律

   在一定时间内，在其他商品的消费数量保持不变的条件下，随着消费者对某
   种商品消费量的增加，消费者从商品连续增加的每一消费单位中所等到的效
   用增量即边际效用是递减的

4. 货币的边际效用

   货币也符合边际效用递减规律，但是在消费者购买商品时，所拥有的货币数
   量是固定的，所以可以认为消费者在购买商品的时刻货币的边际效用是不变的

5. 消费者均衡

   \begin{cases}
     \frac{MU_1}{p_1} = \frac{MU_2}{p_2} = \cdots = \frac{MU_n}{p_n} = \lambda \\
     p_1x_1 + \cdots + p_nx_n = m \\
   \end{cases}

6. 消费者需求曲线

   $\frac{MU_x}{P} = \lambda$

   $x$ 数量上升时，$MU_x$ 减小，$P$ 减小，$\lambda$ 维持不变，可以推导出需
   求曲线向右下方倾斜

   吉芬商品的需求曲线产生原因：

   一般造成价格上升数量也上升的原因是恐慌，在恐慌的情绪中$\lambda$ 极
   速下降，接近于零，即使$P$ 上升，$MU_x$ 也在下降，$x$ 数量在上升

** 序数效用理论

*** 偏好及特点

1. 偏好

   消费者对商品或者商品的喜好程度。对不同的商品组合而言，消费者的偏好
   意味着确定了这些商品组合之间的次序关系，既偏好关系。 效用其实就是用
   来描述偏好

2. 偏好关系的假设

   - 完备性

   - 传递性

   - 连续性

3. 效用函数

   表示效用偏好关系的正数值函数。效用函数不唯一

*** 无差异曲线

一定时期，带给消费者相同效用水平或满足程度的两种商品的所有组合点轨迹

$u = f(x_1, x_2) = u_0$

四个特征：

1. 离原点越远的无差异曲线代表效用水平越高

2. 同一坐标平面中任意两条无差异曲线不会相交

3. 无差异曲线上任意一点的边际替代率为负，无差异曲线从左上方向右下方倾斜

4. 无差异曲线上边际替代率绝对值有递减倾向，所以无差异曲线凸向原点

*** 商品的边际替代率

在维持效用水平不变的前提下，消费者增加一单位某种商品的消费数量时所需要
放弃的另一种商品的消费数量

*** 商品的边际替代率递减规律

/凸显原点的特征/

在维持效用水平不变的前提下，随着一种商品的消费数量的连续增加，消费者为
得到每一单位的这种商品所需放弃的另一种商品的消费数量是递减的

*** 边际替代率与边际效用的关系

/联系基数效用和序数效用/

$RCS_{1,2} = MRS_{1, 2} = - \frac{\Delta x_{2}}{ \Delta
x_{1}} |_{u=u_{0}} = \frac{MU_{1}}{MU_{2}}$

推导过程：

\begin{aligned}
& \Delta u = \Delta x_{1} \cdot MU_{1} + \Delta x_{2} \cdot MU_{2} = 0 \\
& \implies -\frac{\Delta x_2}{\Delta x_1} = \frac{MU_1}{MU_2} \\
\end{aligned}

*** 消费者的预算约束

**** 消费者预算线

在一定的消费者收入和商品价格条件下，消费者全部收入所能购买的两种商品的
不同数量的最大组合。 $P_1X_1 + P_2X_2 = I$

**** 预算线的变动

1. 收入变动，平行移动
   
2. 相对价格变动，转动

*** 消费者均衡（等斜率+耗光）

\begin{aligned}
  & MRS_{1,2} = \frac{p_1}{p_2} = \frac{MU_1}{MU_2} \implies \frac{MU_1}{p_1} = \frac{MU_2}{p_2} \\
  & p_1x_1 + p_2x_2 = I \\
\end{aligned}

*** 消费者均衡的比较静态分析

**** 收入-消费扩展线

在消费者的偏好和商品的价格不变的条件下，消费者收入变动引起的消费者效用
最大化的均衡点的轨迹。它反应收入变化引起的消费量的变动情况。

/可以推导恩格尔曲线/

**** 价格-消费扩展线

指收入不变条件下，商品价格变动引起的消费者均衡点移动的轨迹。它反应价格
变化引起的需求量变动的情况。

*可以推导消费者需求曲线*

**** 需求曲线

*** 替代效应和收入效应

- 总效应

  一种商品的价格变动引起的该商品的数量变动，分为替代效应和收入效应

- 替代效应

  一种商品价格的变动引起商品相对价格的变动（预算线斜率变动），从而引起
  的商品数量变动 (维持效用不变）

- 收入效应

  商品价格变动引起的实际收入变动，从而引起的商品数量的变动

| 商品类 | 价格变化 | 总效应 | 替代效应 | 收入效应                  |
|--------+----------+--------+----------+---------------------------|
| 正常品 | 下降     | 增加   | 增加     | 增加                      |
| 正常品 | 上涨     | 减少   | 减少     | 减少                      |
| 低档品 | 下降     | 增加   | 增加     | 减小（收入效应<替代效应） |
| 低档品 | 上涨     | 减少   | 减少     | 增加（收入效应<替代效应） |
| 吉芬品 | 下降     | 减少   | 增加     | 减小（收入效应>替代效应） |
| 吉芬品 | 上涨     | 增加   | 减少     | 增加（收入效应>替代效应） |

* 生产和成本论                                                     :2020计算:

** 生产函数

在一定时期内，在技术水平不变的情况下，生产中所用的各种生产要素的数量与
所能生产的最大产量之间的关系。

$Q = Af(L, K, N, E, etc.)$

简化后为：

$Q = f(L, K)$

简化的原因：

- $A$ 代表科学进步，对公司来说可以做为外生变量

- $N$ 代表自然资源，可以使用$K$ 来购买

- $E$ 代表企业家才干，需要长时间的积累，短期不变

*** 常见的生产函数

1. 柯布-道格拉斯(C-D)生产函数：$Q = AL^{\alpha}K^{\beta}$
   
   1. $\alpha + \beta > 1$ 规模报酬递增（IRS）

   2. $\alpha + \beta = 1$ 规模报酬不变（CRS）

   3. $\alpha + \beta < 1$ 规模报酬递减（DRS）

2. 完全替代生产函数：$Q = aL + bK$

3. 完全互补生产函数：$Q = min \lbrace \frac{L}{a}, \frac{K}{b}
   \rbrace$

** 短期与长期

- 微观中短期指至少一种生产要素的数量是固定不变的时期，而长期则是指全部
  生产要素的数量都可以变动的时期。

- 宏观中短期指物价不变的时期，长期则是物价可变的时期。

** 短期生产函数

*** 定义

1. 总产量 $TP_L = f(L)$

2. 平均产量 $AL_L = \frac{TP_L}{L} = \frac{f(L)}{L}$

3. 边际产量 $MP_L = \frac{\Delta TP_L}{\Delta L}$

   在其它条件不变的条件下，每增加一单位的劳动所能生产的总产出的增加量

*** 边际报酬递减规律

在技术水平和其他要素投入量不变的条件下，连续的增加一种可变生产要素的投
入量，当这种可变生产要素的投入量小于某一阈值时，增加该要素的投入量所带
来的边际产量是递增的，当超过这一阈值时，增加该要素的投入量所带来的边际
产量是递减的

*** 总产量、平均产量和边际产量曲线

1. 边际报酬递减规律的阈值 $MP_L$ 最大点

2. 平均产量最大的点 $MP_L = AP_L$

3. 最大产量的点 $MP_L = 0$

4. 生产的合理区间：*平均产量最大的点到最大产量的点之间*

** 长期生产函数

*** 意义

在长期内，在技术水平不变的条件下，两种可变要素投入量的组合与能生产的最
大产量的依存关系

*** 等产量曲线

在技术水平不变的条件下，生产同一产量的两种生产要素投入的所有不同组合点
的轨迹

特征：

1. 向右下方倾斜

2. 离原点越远产量越高

3. 任意两条不会相交

4. 凸向原点

*** 边际技术替代率

在维持产量水平不变的条件下，增加一单位某种生产要素投入量时所减少的另一
种要素投入量

$MRTS_{L,K} = RTS_{L,K} = - \frac{dK}{dL} = \frac{MP_L}{MP_K}$

*** 边际技术替代率递减规律（凸向原点的原因）

在维持产量不变的前提下，当一种要素的投入量不断增加是，每一单位的这种要
素所能代替的另一种生产要素的数量是递减的

*** 规模收益（规模报酬）

分析厂商投入结构不发生变动的条件下生产规模的变动与产量变动之间的关系

1. 规模报酬递增

2. 规模报酬不变

3. 规模报酬递减

** 长期生产要素的最优组合

*** 等成本线方程

$C = w \cdot L + r \cdot K$

*** 生产者行为（利润最大化）

\begin{aligned}
 & \pi = TR - TC \\
 & \pi = P \cdot f(L, K) - (w \cdot L + r \cdot K) \\
 & \text{对函数求偏导} \\
 & \begin{cases}
    \frac{d\pi}{dL} = 0 \implies P*MP_L(L, K) = w \\
    \frac{d\pi}{dK} = 0 \implies P*MP_K(L, K) = r \\
 \end{cases} \\
 & \text{两个偏导方程相除} \\
 & \frac{MP_L(L, K)}{MP_K(L, K)} = \frac{w}{r} \\
\end{aligned}

*** 生产要素的最优组合

- 固定成本

  \begin{cases}
    \frac{MP_L(L, K)}{MP_K(L, K)} = \frac{w}{r} \qquad \text{等斜率} \\
    w \cdot L + r \cdot = c \qquad \text{等成本} \\
  \end{cases}

- 固定产量
  
  \begin{cases}
    \frac{MP_L(L, K)}{MP_K(L, K)} = \frac{w}{r} \qquad \text{等斜率}\\
    f(L, K) = y \qquad \text{等产量} \\
  \end{cases}

*** 生产的扩展线

其他条件不变的条件下，成本规模增加，生产要素最优组合的轨迹。

$\frac{MP_L(L, K)}{MP_K(L, K)} = \frac{w}{r}$

** 厂商的生产成本

*** 会计成本和机会成本

- 会计成本

  厂商实际支付的费用

- 机会成本

  指将一定资源用作某种用途时所放弃的其他各种用途中的最大收入，或者是将
  一定资源保持在这种用途上必须支付的成本

*** 显性成本和隐性成本

- 显性成本

  厂商在要素市场上购买或者租用生产要素投入所需要的实际支出

- 隐性成本

  厂商使用自己的生产要素所必须支付的机会成本

*** 私人成本和社会成本

- 私人成本

  一种行为的当事人因为该行为而需要支付的成本

- 社会成本

  一种行为给全社会造成的成本，其中既包含经济当事人本身承担的成本，也包
  含其他经济单位承担的成本。（养鸡场例子，外部性）

*** 短期成本和长期成本

- 短期成本

  考察期内，厂商不能够对所有生产要素加以调整，即至少有一种成本保持不变，
  这种成本被称为短期成本

- 长期成本

  考察期内，所有成本都能够发生变化

** 短期成本

*** 成本分类

1. 总量类

   - 总固定成本（Total Fixed Cost) $TFC = r * \bar K$

   - 总可变成本（Total Variable Cost）$TVC = w * L(Q)$

   - 总成本（Total Cost）$TC = TFC + TVC$

2. 平均类

   - 平均固定成本（Average Fixed Cost）$AFC = \frac{TFC}{Q}$

   - 平均可变成本（Average Variable Cost）$AVC = \frac{TVC}{Q} =
     \frac{w \cdot L}{Q} = w \cdot \frac{1}{AP_L}$

   - 平均成本（Average Cost）$AC = \frac{TC}{Q} = AFC + AVC$

3. 边际类

   - 边际成本（Marginal Cost）$MC = \frac{dTC}{dQ} = \frac{TVC}{dQ} =
     \frac{w \cdot dL}{dQ} = w \cdot \frac{1}{MP_L}$

*** 短期成本曲线推导

边际报酬递减率推导边际产量，边际产量$MP_L$ 推导边际成本$MC$ ，边际成本
推导总可变成本$TVC$ ，总可变成本推导平均可变成本$AVC$

- MC，AVC，AC都是U型曲线

- MC的右半支穿过AVC和AC的最低点

- AVC与AC无限靠近

** 长期成本

*** 长期总成本

指厂商长期中在各种产量水平上的最低总成本

\begin{cases}
    MRTS_{L,K} = \frac{MP_L}{MP_K} = \frac{W}{r} \\
    C = w \cdot L + r \cdot K \\
    y = f(L, K)
\end{cases}

消除方程组中的L和K，则等到C与Q的关系

*** 长期成本曲线

/此处应该有图比较好理解【待补充】/

1. 长期总成本
   
   $LTC = min \lbrace STC_i(Q) \rbrace$

   LTC是短期成本STC的包络线

2. 长期平均成本

   $LAC = min \lbrace \frac{STC_i{Q}}{Q} \rbrace$

   LAC是短期平均成本SAC的包络线

3. 长期边际成本

   /同短期形状差不多，U型，右半支穿过LAC最低点/

*** 规模经济与长期平均成本

*规模经济与规模报酬的概念不同，规模经济不要求生产要素投入机构不变，而
规模报酬要求生产要素投入成比例变化*

1. 规模经济

   对于一个厂商而言，如果产量扩大一倍，而厂商的成本增加低于一倍，则称
   厂商的上产存在规模经济

2. 规模不经济

   如果产量扩大一本，而厂商的成本增加大于一倍，则生产存在规模不经济

3. 长期平均成本呈现U型的解释

   在左半支一定规模一下，存在规模经济，而大于生产大于某一规模是生产表
   现出规模不经济

* 市场理论

** 利润最大化条件

利润方程 $\pi = TR(Q) - TC(Q)$

最大化求导，导数为零 $\frac{d\pi}{dQ} = \frac{dTR(Q)}{dQ} -
\frac{dTC(Q)}{dQ} = 0$

导数为零的条件 $\frac{dTR(Q)}{dQ} = \frac{dTC(Q)}{dQ}$

最终得到 $MR(Q) = MC(Q)$ 

*注意* ，这里导数为零只是利润最大化的必要条件，不是充分条件，导数为零也
可能是利润最小的点

利润最大化中MR是市场决定，MC由企业决定，本章主要探讨不同市场的MR

** 不同市场划分

| 市场         | 企业数量                   | 价格控制力                   | 产品差异化程度   | 企业进入行业难易程度 | 例子               |
|--------------+----------------------------+------------------------------+------------------+----------------------+--------------------|
| 完全竞争市场 | 多                         | 市场价格的接受者             | 无               | 自由                 | 同一地区农产品市场 |
| 垄断竞争市场 | 数量多规模小               | 有一定控制力                 | 有差别的同种产品 | 相对容易             | 饭店，酒店         |
| 寡头垄断市场 | 少数厂商，规模大，相互依存 | 有明显控制力，但价格相对稳定 | 不确定           | 比较困难             | 银行，石油         |
| 垄断市场     | 只有一家                   | 厂商定价                     | 无               | 难                   | 铁路，电网         |

** 完全竞争市场

*** MR的决定

\begin{cases}
  TR(Q) = P \cdot Q \\
  AR(Q) = \frac{TR(Q)}{Q} = P \\
  MR(Q) = \frac{dTR(Q)}{dQ} = \frac{d(P \cdot Q)}{dQ} = P \\
\end{cases}

*** 完全竞争市场的厂商短期均衡

短期厂商的生产成本曲线无法调整（线动）所以均衡讨论的是市场价格与厂商成
本曲线的5种相交情况

/这里有图比较好【待补充】/

1. $P > min(AC)$ ，企业盈利 $\pi = P * Q^*|_{MC(Q) = P}$
   
2. $P = min(AC)$ ，企业的盈亏平衡点

3. $min(AVC) < P < min(AC)$ ，企业亏损，但是选择继续生产，因为收入大于
   平均可变成本

4. $P = min(AVC)$ ，企业关门的临界点

5. $P < min(AVC)$ ，企业关门

*** 完全竞争市场的短期供给曲线

$P > min(AVC)$ 时的企业$MC(Q)$ 曲线

*** 完全竞争市场的厂商产期均衡

完全竞争市场厂商进入退出自由，所有最终的均衡为

$P = AR = MR = min(LAC) = LMC = SMC_i = min(SAC_i)$

此时厂商的利润为0

市场上厂商的数量可以通过市场总需求量除以单个厂商供给量得出

*** 行业的长期供给曲线

1. 外在经济和外在不经济

   随着厂商数量的增加，整个行业中的产量也会增加，如果行业中单个缠上的
   成本降低，则称该行业存在外在经济。反之，存在外在不经济。

2. 成本不变行业的长期供给曲线：水平线

3. 成本递增行业的长期供给曲线：向右上方倾斜

4. 成本递减行业的长期供给曲线：向右下方倾斜

** 垄断市场

*** 垄断市场结构及其特征

一家厂商控制了某种产品全部供给的市场结构

*** 垄断市场的MR确定

\begin{cases}
  TR(Q) = P(Q) \cdot Q \\
  MR(Q) = \frac{dTR(Q)}{dQ} = \frac{d(P(Q) \cdot Q)}{dQ} \\
  MR(Q) = \frac{dP}{dQ}Q + P \cdot \frac{dQ}{dQ} = P \cdot (1 + \frac{dP}{dQ} \cdot \frac{Q}{P}) \\
  MR(Q) = P \cdot (1 - \frac{1}{|e|})
\end{cases}

从需求曲线上看，MR线穿过需求曲线在P上截距和需求曲线Q轴截距的中点

*** 垄断市场的条件

1. 市场上只有唯一的一个厂商生产和销售商品

2. 该厂商生产和销售的商品没有任何相近的替代品

3. 其他任何厂商进入该行业都极为困难或者不可能

4. 厂商具有定价权

*** 垄断厂商的短期均衡

/画图分析/

*** 垄断厂商的长期均衡

$MR = LMC$

*** 价格歧视

同一厂商在同一时间对同一种产品向不同的购买者索取两种或两种以上的价格

价格歧视分类：

1. 一级价格歧视

   完全价格歧视，厂商根据消费者意愿为每单位商品付出的最高价格而为每单
   位产品制定不同的销售价格

2. 二级价格歧视

   垄断厂商根据不同的购买量和消费者确定价格

3. 三级价格歧视

   垄断厂商对同一种铲平在不同的市场上，或不同的消费者群体，收取不同的
   价格

** 垄断竞争市场

*** 垄断市场的长期均衡条件

$MR = LMC, AR = LAC$

*** 垄断竞争市场的条件

1. 企业生产有差别的同种产品，这些产品彼此之间都是非常接近的替代品

2. 一个生产集团中的企业数量非常多，以至于*每个厂商都认为自己的行为的影
   响很小*，不会引起竞争对手的注意和反应

3. 厂商的生产规模比较小，进入或者退出是自由的

4. 厂商有一定的定价权

*** 主观需求曲线与客观需求曲线

1. 主观需求曲线

   单个厂商单独采取行动时所面临的需求曲线。也叫单个厂商的需求曲线

2. 客观需求曲线

   行业中所有企业都采取相同的行动时，单个厂商所面临的需求曲线。也叫市
   场份额曲线

3. 单个厂商的需求曲线比客观需求曲线要平缓一些

** 寡头市场

*** 寡头市场的特征

1. 市场上存在少数厂商，单个厂商的销量占整个市场相当大的份额，进而对价
   格有明显的影响力

2. 少数寡头之间的行为相互依存

3. 寡头市场上的价格相对稳定

4. 市场存在进入壁垒

*** 古诺模型（数量竞争模型）

**** 两个假设

1. 双寡头

2. 生产零成本

   这个假设意味着$MC = 0$ ，厂商利润最大化的点（$MR = MC = 0$ ）即是需
   求曲线Q轴截距的中点

**** 结论

\begin{cases}
  \frac{1}{3} \cdot Q_1, & n = 2 \\
  \frac{1}{n+1} \cdot Q_1, & n > 2 & n\text{为厂商数量}, Q_1\text{为市场容量} \\
\end{cases}

*** 斯威齐模型（弯折的需求曲线模型）

当一个寡头厂商提高价格时，其他厂商不会跟随，但若它降低价格时，其他厂商
也会如此，结果单一厂商面临的需求曲线具有一个弯折点

*** 卡特尔模型

/掌握计算题/

*** 博弈论

**** 基础概念

参与方相互影响的情况下，如何作出最优决策的分析方法

包含：

1. 参与者

2. 行动

3. 规则

**** 占优策略均衡

无论其他参与者采取什么策略，某参与者的唯一的最优策略就是他的占优策略。
由博弈所有参与者的占优策略组合所构成的均衡就是占优策略均衡

**** 纳什均衡

指的是参与人的这样一种策略组合，在该策略组合上，任何参与人单独改变策略
都不会得到好处。换句话说，如果在一个策略组合上，当所有其他人都不改变策
略时，没有人会改变自己的策略，则该策略组合就是一个纳什均衡

* 生产要素市场

** 生产要素市场一般原则

*** 直接需求与引致需求

1. 直接需求

   消费者对产品的需求

2. 引致需求

   由消费者对产品的直接需求所引发的厂商对生产要素的需求被称为引致需求

*** 厂商利润最大化的原则

$\pi = TR(L) - TC(L)$

最大化导数为0:

$\frac{dTR(L)}{dL} - \frac{dTC(L)}{dL} = 0$

$\frac{dTR(L)}{dL} = \frac{dTR}{dQ} \cdot \frac{dQ}{dL}  = \frac{dTC(L)}{dL}$

$MRP = MR \cdot MP  = MFC$

$MRP$ 为生产要素的边际收益，叫边际收益产品

$MPC$ 为生产要素的边际成本，叫做边际要素成本

*对于完全竞争市场* ，$MR = P$ ，$MRP = P \cdot MP = VMP = MFC$

$VMP$ 叫做边际产品价值

*** 完全竞争市场的要素需求曲线

/参考大纲和教材/

** 劳动供给和工资率的确定

*** 劳动与闲暇的替代效应与收入效应

- 替代效应

  闲暇的需求量与闲暇的价格反方向变化

- 收入效应

  闲暇的需求量与闲暇的价格正方向变化

- 总效应取决与替代效应与收入效应的大小

** 欧拉定理

*** 欧拉定理（产品分配尽净定理）

在完全竞争条件下，如果规模报酬不变，则全部产品正好足够分配给各个生产要
素，不多也不少

假设：$Q = Q(L, K)$

则：

$Q = L \cdot \frac{\delta Q}{\delta L} + K \cdot \frac{\delta
Q}{\delta K}$

$Q = L \cdot MP_L + K \cdot MP_K$

** 洛伦兹曲线和基尼系数

/大纲中没有，参考教材/

* 一般均衡与福利经济学

** 一般均衡基本概念

*** 局部均衡和一般均衡

1. 局部均衡

   在其他条件不变的情况下考察单个经济单位或市场的大分析是局部均衡，所
   涉及到的理论属于局部均衡范畴

2. 一般均衡

   将所有市场看成一个整体加以研究而进行的分析是一般均衡分析，相应的理
   论就是一般均衡理论

*** 一般均衡的基本思想

*** 一般均衡的存在性问题

- 瓦尔拉斯定理

  对整个经济系统而言，所有的收入之和一定等于所有的支出之和

  $\sum p_i x_i = \sum p_i y_i$

  完全竞争市场条件下，存在着一个价格体系，使得一般均衡实现

** 纯交换经济的一般均衡

*** 埃奇沃斯框图

埃奇沃斯框图指方形的长和高分别代表两个消费者（或生产者）所拥有的两种商
品（或生产要素）的总量，盒状图中各点表示两种商品（或要素）的总供给量在
两个消费者（生产者）之间的配置状态

两个消费者（或者生产者）无差异曲线的相切点的轨迹就是契约曲线线，契约曲
线上的资源分配都符合拍累托最优，但是可能存在分配不公

** 帕累托最优                                                     :2020重点:

*** 帕累托最优

经济状态的任何改变都不能使此状态中的任何一个人的境况变得更好而不使别人
的境况变坏，或者说如果不使别人的境况变坏，就无法使任何一个人的境况变得
更好，这种经济状态就称为帕累托最优

*** 帕累托改进

如果既定的资源配置状态的改变，能够让一部分社会成员的状况改善，而其他人
的状况并没有变坏，这就可以看作是一种资源配置的改善，称为帕累托改进

*** 生产可能性边界

*这个概念在这里出现有点儿奇怪，只是和帕累托生产和交换最优条件相关，之
前没有出场的时机，所以在这里补充，国际经济学中也有用到*

厂商将所有的要素$(L, K)$ 全部投入生产产品$(X, Y)$ 两种产品，所能得到的
最大产量的组合轨迹

生产可能性边界的斜率叫$MRT$ 边际转换率

*** 帕累托最优的条件

- 消费者的帕累托最优

  $MRS_{XY}^A = MRS_{XY}^B$

- 生产的帕累托最优

  $MRTS_{LK}^C = MRTS_{LK}^D$

- 生产和交换的帕累托最优

  $MRS_{XY}^A = MRT_{XY}^C$

** 完全竞争市场和帕累托最优

/证明完全竞争市场可以实现帕累托最优/

- 消费者的拍累托最优

  $MRS_{XY}^A = MRS_{XY}^B = \frac{P_X}{P_Y}$

- 生产的帕累托最优

  $MRTS_{XY}^C = MRTS_{XY}^D = \frac{w}{r}$

- 生产和交换的拍累托最优

  $MRT_{XY}^C = - \frac{\Delta Y}{\Delta X}$

  意思是减少生产一单位X产品，可以增加多少Y产品的生产可以表示为
  $\frac{MC_X}{MC_Y}$

  因为完全竞争市场$P_X = MR_X = MC_X, P_Y = MR_Y = MC_Y$

  所以
  
  $MRT_{XY}^C = \frac{MC_X}{MC_Y} = \frac{P_X}{P_Y} = MRS_{XY}^A$

* 市场失灵与微观经济政策

** 市场失灵及类型

*** 市场失灵

指市场机制不能有效的配置资源（实现帕累托最优）。

- 狭义的市场失灵

  指完全竞争市场所假定的条件得不到满足而导致的市场配置资源的能力不足从
  而缺乏效率的表现。

- 广义的市场失灵

  还包括市场机制在配置资源过程中所出现的经济波动以及按市场分配原则导致
  的收入分配不公的现象。

*** 类型

- 不完全信息（非对称信息）

- 垄断

- 外部性

- 公共物品（财政学主要关注的）

** 垄断

价高量少无效率

对策：

- 限价反垄断有效

- 开放市场反垄断有效

- 征税反垄断无效

** 外部性

*** 外部性含义

指一个经济主体的行为对另一个经济主体的福利所产生的影响，而这种影响并没
有通过货币或市场交易反映出来。外部性有正负之分，称为外在经济和外在不经
济

*** 对策

1. 税收与津贴

2. 外部影响内部化（合并）

3. 规定产权（科斯定理）

   在交易成本为零时，只要产权初始界定是清晰的，并允许当事人进行自由谈
   判，那么无论开始时将产权赋予谁，市场均衡的最终结果都会达到资源的有
   效配置

** 公共物品

*** 公共物品含义

既无竞争性又无排他性的物品通常被称为公共物品

- 排他性

  商品的生产者或者购买者可以很容易地把他人排斥在获得该商品带来的利益之
  外

- 竞争性

  消费商品的数量与生产这一数量的成本有关

*** 免费乘车问题

在公共物品的消费上隐瞒自己的真实偏好，以图“搭便车”，从而出现市场失灵

** 不对称信息

*** 不对称信息含义

不同经济主体拥有的信息量不想等或不平衡

- 逆向选择

低质量产品将高质量产品驱逐出市场的现象

- 道德风险

有信息优势的一方，在签订合同后，有可能采取有悖于合同规定的行为，以最大
化自己的利益，同时损害另一交易方的利益

*** 解决对策

- 激励合同

- 信息披露

* 宏观经济活动与宏观经济学

** 宏观经济学的特点

- 微观经济学：价格理论

- 宏观经济学：收入理论


** 国内生产总值

*** 国内生产总值（GDP）

经济社会（一国或一地区）在一定时期内运用生产要素所生产的全部最终产品
（物品和劳务）的市场价值

隐含的经济意义

1. 产出等于价值增值

2. 产出等于收入

3. 产出等于支出（存货看作厂商对自己商品的购买）

需要注意的

1. GDP是一个市场价值的概念

2. GDP的测度是最终产品的价值，中间产品不计入，否则会造成重复计算

3. GDP是一定时期内（往往为一年）所生产而不是所销售掉的最终产品的价值

*** GDP核算方法

**** 支出法

用整个社会购买最终产品的总支出核算GDP（从总支出或者总需求角度），现实
生活中，产品和劳务的最终使用是由居民购买、企业投资购买、政府购买和国外
购买构成。

$GDP = C + I + G + (X - M)$

**** 收入法

用要素收入，即企业生产成本核算国内生产总值

$GDP = L(工资) + K(利息) + E(利润) + N(租金) + 间接税和企业转移支付 +
折旧$

*** 几个重要的国民收入变量

1. 国内生产总值（GDP）

2. 国内生产净值（NDP）

   $NDP = GDP - \text{折旧}$

3. 国民收入（NI）

   $NI = NDP - (\text{间接税} + \text{企业转移支付}) + \text{政府补助}$

4. 个人收入（PI）

   $PI = NI - \text{企业留存} + \text{政府补助}$

5. 个人可支配收入（DPI）

   $DPI = PI - \text{税收}$

*** 国民收入恒等式

\begin{cases}
  AE(总支出) & = C + I + G + NX \\
  AS(总收入) & = C + S + T + Kr \\
\end{cases}

/$Kr$ 为转移支付，给国外的资本，一般不考虑/

**** 两部门经济（简单经济）

消费者、企业

\begin{cases}
  AE(总支出) & = C + I \\
  AS(总收入) & = C + S \\
  AE = AS \\
  I = S \\
\end{cases}

**** 三部门经济（封闭经济）

消费者、企业、政府

\begin{cases}
  AE(总支出) & = C + I + G \\
  AS(总收入) & = C + S + T \\
  AE = AS \\
  I = S + (T - G) \\
\end{cases}

$T - G$ 可以看作是政府的储蓄

**** 四部门经济（开放经济）

\begin{cases}
  AE(总支出) & = C + I + G + NX \\
  AS(总收入) & = C + S + T + Kr \\
  AE = AS \\
  I = S + (T - G) + (Kr - Nx) \\
\end{cases}

$Kr - Nx$ 相当与外国的储蓄

* 简单国民收入决定理论

*国民收入受哪些因素影响*

** 消费函数与需求函数

*** 总需求（总支出）的构成

总支出（总需求）指经济中各个部门对物品和劳务的支出总量，用$E$ 表示总支
出（总需求）。

$E = C + I$

均衡条件：$Y = E = C + I$

*** 消费函数

$C = \alpha + \beta Y$

$\alpha$ 为自发消费（没收入也要消费）

$\beta$ 为边际消费倾向（MPC），大于0，小于等于1

\begin{cases}
  Y = C + I \\
  C = \alpha + \beta Y \\
  Y = \frac{\alpha + I}{1 - \beta} \\
\end{cases}

*** 储蓄函数

$Y = C + S$

$S = Y - (\alpha + \beta Y)$

$S = - alpha + (1 - \beta)Y$

$1 - \beta$ 边际储蓄倾向（MPS），MPS + MPC = 1

*** 消费函数与储蓄函数的关系

$Y = C + S$

$\frac{C}{Y} + \frac{S}{Y} = 1$

$\frac{C}{Y}$ 为平均消费倾向（APS）

$\frac{S}{Y}$ 为平均消费倾向（APC）

$MPS + MPC = 1$

** 国民收入决定

*** 两部门经济

$Y = \frac{\alpha + I}{1 - \beta}$

*** 三部门经济

\begin{cases}
  Y = C + I + G \\
  C = \alpha + \beta(Y - T) + I + G \\
\end{cases}

$Y = \frac{\alpha - \beta T + I + G}{1 - \beta}$

*** 四部门经济

$Y = \frac{\alpha - \beta T + I + G + NX}{1 - \beta}$

*** 注意

** 乘数理论

*** 投资乘数

收入的变化与带来这种变化的投资支出变化的比率

$k_I = \frac{\Delta y}{\Delta i} = \frac{1}{1 - MPC} = \frac{1}{1 -
\beta}$

结论，国民收入的增长会数倍于投资乘数的增长

*** 政府购买乘数

收入的变化与引起这种变化的政府投资变动的比率

$k_G = \frac{1}{1 - MPC} = \frac{1}{1 - \beta}$

*** 税收乘数

收入的变化与引起这种变化的税收变动的比率

$k_T = \frac{-\beta}{1 - \beta} = \frac{-MPC}{1-MPC}$

*** 平衡预算乘数

政府收入和支出同时以相等数量增加或减少是，国民收入变动与政府收支变动的
比率

$k_b = k_G + K_T = 1$

政府通过税收收钱，在全部花光，是有效率的（维持经济增长）

* 产品市场与货币市场的一般均衡

/前一章中，投资（I）被看做是一个外生变量来讨论，这一章引入利率与投资的
关系，再来讨论会如何影响总产出（Y）的增长/

** 投资的决定

*** 投资的边际效率（MEC）

是一种贴现率，这种贴现率正好使得一项资本物品的使用期限内各项预期收益的
现值之和等于这项资本物品的供给价格或者重置成本

$R_0 = \frac{R_1}{1 + r_c} + \frac{R_2}{(1 + r_c)^2} + \cdots +
\frac{R_n}{(1 + r_c)^n}$

*** 投资决定

投资的条件是$r_c > r$ ，资本边际效率大于市场的利息率，赚的钱大于借钱的
成本

*** 投资函数

$I = I(MEC, r)$ ，固定MEC不变，则简化为只与利率相关的函数$I =
I(\overline{MEC}, r) = I(r)$

凯恩斯的理论中

$I = e - d \cdot r \quad (d > 0)$

$e$ 表示自主投资

$d$ 表示投资对利率的敏感系数

** IS曲线及其推导

\begin{cases}
  Y = AD \\
  AD = C + I + G \\
  I = e - d \cdot Y \\
  C = \alpha + \beta Y \\
\end{cases}

$r = - \frac{1-\beta}{d}Y + \frac{\alpha - \beta T + e + G}{d}$

IS曲线表示产品市场均衡时（AS=AD），利率与总产出之间的关系

** LM曲线及其推导

L（Liquidity）货币需求与M（Money Supply）货币供给之间的均衡

*** 货币需求

**** 货币需求的动机

- 交易动机

  指个人和企业需要货币是为了进行正常的交易活动

- 谨慎或预防动机

  指为预防意外支出而持有一部分货币的动机

- 投机动机

  指人们为了抓住有利的购买有价证劵的机会而持有一部分货币的动机

**** 货币需求函数

$L = L_1(Y) + L_2(r) = k \cdot Y - h \cdot r$

**** 流动偏好陷阱

当利率极低，人们会认为这时利率不大可能再下降，或者说有价证劵市场价格不
大可能再上升只会跌落，因而人们会将所持有的有价证劵全部换成货币，即使有
了货币也不会去购买有价证券，以免证劵价格下跌而遭受损失。这种人们不管有
多少货币都愿意持在手中，而不愿去购买有价证券的情况被成为“凯恩斯陷阱”或
者“流动性陷阱”

*** 货币供给

1. $M$ 为名义货币供给， $m$ 为实际货币供给，$m = \frac{M}{P}$

2. 货币供给通常是常数，由央行决定

*** LM曲线的推导

$m = L = L_1 + L_2 = L_1(y) + L_2(r) = k \cdot y - h \cdot r$

$r = \frac{k}{h} \cdot y - \frac{m}{h}$

** 产品市场与货币市场同时均衡

*** IS-LM模型

*注意* IS-LM为短期市场的均衡，蕴含了价格是常数的意义

\begin{cases}
  IS: \quad I(r) = S(y) \implies r = - \frac{1-\beta}{d}Y + \frac{\alpha - \beta T + e + G}{d} \\
  LM: \quad L_1(y) + L_2(r) = m \implies r = \frac{k}{h} \cdot y - \frac{m}{h} \\
\end{cases}

** 凯恩斯理论的基本框架

*** 凯恩斯理论认为萧条的三大原因

1. 边际消费倾向递减

2. 流动性陷阱

3. 预期收益率不高

* 宏观经济政策

** 宏观经济政策概述

*** 宏观经济政策目标

- 充分就业

- 价格稳定

- 经济增长

- 国际收支平衡

- 产业结构高级化（社会主义经济学中增加）

*** 宏观经济政策理论基础

财政政策移动IS曲线，货币政策移动LM曲线。而且向右移动表示扩张，向左移动
表示紧缩。

** 财政政策

*** 财政政策

政府变动税收和支出以便影响总需求进而影响就业和国民收入的政策。

*** 自动稳定器

自动稳定器又称为“内在稳定器”。在国民经济中无需经常变动政府政策而有助于
经济自动趋向稳定的因素。

- 个人和公司所得税

  经济萧条，政府税收下降，相当于增加的政府投资。

- 失业补助和其他福利转移支付

  经济萧条，政府失业补助和福利转移支付增加，拉动需求。

- 农产品维持价格以及公司储蓄和家庭储蓄

*** 斟酌使用财政政策

逆风向行事（购买、支付、税收和公债）

- 经济衰退时，扩大政府支出，减少财政收入

- 经济过热时，削减财政支出，增加税收

*** 功能财政和政府充分就业预算盈余

**** 功能财政

不以财政预算收支平衡的观点来对待预算平衡和预算赤字，而应该从反周期的需
要来利用预算赤字和预算盈余。当国民收入低于从分就业的收入水平时，即使出
现财政赤字，政府也应该采取扩张性财政政策。

**** 充分就业的预算盈余

指既定的政府预算在充分就业的国民收入水平即潜在的国民收入水平上所产生的
政府预算盈余，即潜在国民收入对应的财政收入和政府预算支出之间的差额。以
此为表征，可以消除收入的周期性波动对预算状况的影响。

**** 挤出效应

指政府支出增加所引起的私人消费和投资降低的效果，进而是的GDP增长达不到
乘数效应时的潜在产出。

影响因素

- 支出乘数的大小

- 货币需求对产出变动的敏感程度

- 货币需求对利率变动的敏感程度

- 投资需求对利率变动的敏感程度

** 货币政策

中央银行通过银行体系变动货币供给量来调节总需求的政策

*详细参考《货币银行学》第7章*

货币政策措施：

1. 再贴现率

2. 公开市场业务

   中央银行在金融市场上公开买卖政府证劵以控制货币供给和利率的政策行为。

3. 法定准备金

   央行规定商业银行必须按照一定比率将吸收到的存款存放到中央银行以规避
   风险。

4. 其他手段：道义劝告、放宽信贷条件、信贷配额等

* 总需求与总供给分析

** 理解AD-AS分析需要注意的地方

1. 不同与IS-LM模型，AD-AS模型是长期模型，意味着价格可以变化

** 总需求及其推导

*** 总需求

总需求函数就是描述在各个价格水平下经济社会需要多高的产量水平

$p = P_{AS}(y)$

*** 推导

\begin{cases}
  IS: \quad I(r) = S(y) \implies r = - \frac{1-\beta}{d}Y + \frac{\alpha - \beta T + e + G}{d} \\
  LM: \quad L_1(y) + L_2(r) = m \implies r = \frac{k}{h} \cdot y - \frac{m}{h} \\
  m = \frac{M}{P}
\end{cases}

消除变量$r$ 可以等到价格水平$P$ 与产量$y$ 之间的关系

*** 图形推导

/参考大纲或着教材/

** 总供给的一般说明

*** 总供给函数

总供给函数反映的是在各个不同的价格水平上，厂商愿意提供的总产出水平，总
供给曲线体现了价格水平通过生产要素市场来影响产出

*** 劳动市场的均衡

*** 总供给曲线的图形推导

/参考大纲或教材，这里稍微有点儿绕/

*** 长期的供给曲线

一条竖直线

*** 完整的供给曲线

短期（凯恩斯，水平线）、正常（向右上倾斜）、长期（竖直线）

** AD-AS模型的均衡及其政策含义

理解下面几种情况的含义

1. AD-AS相交与凯恩斯区域

   存在失业，采用扩张性宏观政策，产出增加，物价水平保持不变

2. AD-AS相交与正常区域

   扩张性宏观政策，产出增加，物价水平上升

3. AD-AS相交与长期区域

   产出以达到充分产量，继续扩张性政策，产出不变，物价上涨

结论

- 短期而言，需求管理政策非常有效
  
- 长期而言，需求管理政策无效

* 经济增长

** 经济增长与经济发展

- 经济增长

  指一个国家一定时期生产的产品和服务总量不断增多的过程。（长期）

- 经济发展

  包含经济增长和其他因素（制度、教育、寿命等）

** 哈罗德-多马模型

*** 基本假定

1. 全社会使用劳动和资本两种生产要素只生产一种产品

2. 资本-产出比保持不变

3. 储蓄率即储蓄在收入中所占的比重保持不变

4. 不存在技术进步，也不存在资本折旧

5. 人口按照一个固定速度增长

*** 基本模型

$s$ 表示储蓄率$\frac{S}{Y}$ ，$v$ 表示边际资本-产量比率$\frac{\Delta
K}{\Delta Y}$

$G = \frac{\Delta Y}{Y} = \frac{s}{v}$

经济增长与储蓄率成正比，与资本-产出比成反比

*** 增长条件

$G_A = G_W = G_N$

$G_A$ 是由有效需求决定的实际增长率

$G_W$ 是指有保证的增长率

$G_N$ 是指一国的人口增长率

*** 模型意义

在现实中，由于各种因素的影响，实际增长率、有保证的增长率和自然增长率很
难达到一致，其增长途径成为“刃锋”。

** 新古典增长模型

*** 理论假定

1. 全社会使用劳动和资本两种生产要素只生产一种产品

2. 劳动与资本之间可以相互替代，但并不能完全替代

3. 生产规模收益不变

4. 储蓄率即储蓄在收入中所占的比重保持不变

5. 不存在技术进步，也不存在资本折旧

6. 人口按照一个固定速度增长

*** 基本方程

$\Delta k = s \cdot f(k) - (n + \delta) \cdot k$

$k$ 为人均资本量

投资 = 资本的深化 + 资本的广化

*** 稳定增长的条件

1. 技术进步

2. 降低储蓄率

3. 提高储蓄率

** 新经济增长理论

*** 基本观点

1. 内生因素推动经济增长

2. 技术进步很重要

3. 人力资源、知识积累具有外部性

4. 经济政策可以影响长期增长（产业政策）

* 通货膨胀理论

** 通货膨胀的种类和影响

*** 通货膨胀含义及衡量

- 含义

  一般价格总水平的持续和显著的上涨

- 衡量

  1. 消费者物件指数CPI

  2. 生产者物价指数PPI

  3. GNP折算数

*** 通货膨胀的分类

1. 按照价格上升的速度

   - 温和的通货膨胀（年通货膨胀率<10%）

   - 奔腾的通货膨胀（10%-100%）

   - 超级的通货膨胀（>100%）

2. 按相对价格变动程度区分

   - 平衡的通货膨胀

   - 非平衡的通货膨胀

3. 按人们的预料程度区分

   - 预期到的通货膨胀

   - 未预期到的通货膨胀

*** 通货膨胀的效应

/参《考货币银行学》/

1. 收入和财富分配效应

   - 通货膨胀不利与靠固定的货币收入维持生活的人

   - 通货膨胀对储蓄者不利

   - 通货膨胀还可以影响债务人和债权人利益而使得债务人获益

2. 就业和产量效应

   - 随着通货膨胀的出现，产出增加，收入增加

   - 成本推动型通货膨胀会使得收入或产量减少，从而引致失业

   - 超级通货膨胀导致经济崩溃

** 通货膨胀的原因

*** 需求拉动型

过多的货币追求过少的商品

*** 成本推动型

- 工资推动型

  劳动力市场不完全竞争

- 利润推动型

  不完全竞争的产品市场

*** 混合型通货膨胀

“推中有拉，拉中有推”

*** 结构型通货膨胀

由于经济结构变动引起，生产效率提高快的部门和生产率提高慢的部门，生产要
素很难在部门转移，由于工资刚性造成全部门的工资和价格水平提高

*** 作为货币现象的通货膨胀

$\pi = m - y + v$

** 价格调整曲线

*** 菲利普斯曲线

经济学理论中用来表示失业率和通货膨胀率之间替换关系的曲线

分为短期、长期、滞涨期三种

*** 价格调整方程

$\pi_t = \pi_t^e + (\mu + z) - \alpha u_t$

忽略供给方面的冲击

$\pi_t = \pi_t^e - \alpha u_t$

失业率借用总需求相对于潜在收入的增长率加以表示

$\pi_t = \pi_t^e + h \frac{Y_t - Y_f}{Y_f}$

*** 奥肯定律

失业率与经济增长率之间关系，失业率每高于自然失业率一个白分点，GDP将低
于潜在GDP两个白分点

* 宏观经济学的意见分歧

** 宏观经济学意见分歧

*** 古典宏观经济学和凯恩斯经济学

1. 古典宏观经济学

   指凯恩斯以前的在西方经济学界占统治地位的新古典经济学，是关于整个经
   济社会的产量、就业、货币数量、储蓄、投资、利息率和价格总水平的理论。
   萨伊定律是核心。

2. 凯恩斯主义经济学

   凯恩斯经济学否定了古典宏观经济学的基本假定，认为经济可以以处于低于
   充分就业的状态。在三大心理规律的作用下，消费和投资需求不足，从而导
   致整个经济的总需求不足，经济处于低于充分就业状态，所以需要利用经济
   政策对经济进行干预。

*** 新古典综合派、货币主义、供给学派和理性预期学派

1. 新古典综合派

   指凯恩斯在20世纪20年代创立并为他的追随者所发展的宏观经济理论体系。
   以塞缪尔森、托宾、索洛为代表的凯恩斯主义者，把凯恩斯的经济理论同传
   统的微观经济理论综合在一起，形成了所谓新古典综合派，其主要思想为：

   1. 以马歇尔理论为主的微观经济学

   2. 以凯恩斯理论为核心，利用IS-LM分析说明经济的总需求

   3. 以货币工资下降刚性说明向上倾斜的总供给

   4. 以索洛的新古典增长模型说明经济增长

   5. 以菲利普斯曲线说明价格调整和通货膨胀

2. 货币主义

   从货币理论出发考察宏观总量的变动，认为货币存量的变动是影响经济波动
   的主要因素，他们确信市场机制的自发作用，反对凯恩斯主义所采用的宏观
   经济政策，特别是财政政策。

3. 供给学派

   从凯恩斯主义忽略供给的角度批判凯恩斯理论，主张把经济分析的重点转向
   供给。

4. 理性预期学派

   从理性预期和经纪人的假设出发指出凯恩斯主义理论体系存在的问题，否定
   其政策的有效性。

*** 新古典宏观经济学和新凯恩斯主义经济学

1. 新古典宏观经济学

   是理性预期学派更为广泛的名称，这一学派以批判凯恩斯主义起家，以理性
   预期的市场出清为基本假定分析宏观经济总量决定和经济波动。

2. 新凯恩斯主义经济学

   在原有凯恩斯理论基础上重新对宏观经济理论作出解释的一个流派，它以价
   格黏性和非市场出清为假定条件，尝试把传统的微光经济学与凯恩斯主义的
   宏观经济学结合起来，说明宏观总量的决定，为政府干预提供依据。

** 货币主义

*** 基本命题

货币最要紧，货币的推动力是说明产量、就业和价格变化的最主要因素。货币供
给量的变动是货币推动力的最可靠的度量标准，经济调控应该唯一地通过货币当
局对货币供给量的控制加以调节。

*** 新货币数量论

货币需求主要取决于社会的总财富、非人力财富在总财富中所占的比例和各种非
人力财富的预期报酬率。

结论，第一，价格总水平与货币供给量同方向变化；第二，短期内货币流动速度
会受到利息率的影响，但波动是轻微的。

根据$MV = PV$ ，短期内，$M$ 变动会影响到$Y$ ，但是长期看，$M$ 和$V$ 同
时变动，因而改变货币量不会影响产出。

*** 自然率假说

自然率一般指的是自然失业率，自然失业率为经济社会在正常情况下的失业率，
它是劳动市场处于供求稳定状态时（达到潜在产出）的失业率，这里的稳定状态
被认为是，既不会造成通货膨胀也不会导致通货紧缩的状态。

货币主义认为，长期而言，经济总是趋向与自然失业率。

*** 货币主义政策分析

1. 反对财政政策

2. 反对相机抉择的货币政策

** 新古典宏观经济学

*** 基本假设

1. 理性预期

   指经济当事人对价格、利率和收入等变量未来的变动可以做出符合理性的估计。

   - 预期平均来说是正确的

   - 利用所有有效信息对某个经济变量做出预期

   - 信息包含经济理论，因而结果与经济模型的预期相一致

2. 个人利益最大化

3. 市场出清

   无论劳动力市场的工资还是产品市场上的商品价格都具有充分的灵活性，可
   以根据供求情况迅速进行调整，以达到供求相等的均衡状态。（非黏性）

*** 结论

政策导致经济波动，应该放弃干预经济的行为。

** 新凯恩斯主义经济学

*** 基本假定

1. 非市场出清

   工资和价格等不能迅速调整到使得市场出清的状态。

   - 菜单成本理论

   - 交错调整工资论

   - 不完全竞争理论

2. 经济当事人利益最大化

3. 理性预期
