#+TITLE: 国际经济学
#+STARTUP: indent
#+DATE: <2020-10-14 Wed>
#+OPTIONS: toc:2
#+SETUPFILE: readtheorg-theme.setup

* 考试分数分布

  2个选择题（4分）
  
  1个名词解释（3分）

  1个简答（8分）

  一共15分，难度较大，考题简单

* 绪论

** 国际经济学的基本概念

1. 资源的国际配置

2. 福利的国际最大化分析

3. 国际经济活动往来的内在联系

** 国际经济学的研究内容

1. 国际贸易纯理论研究

2. 国际贸易政策研究

3. 国际收支研究

4. 外汇理论研究

5. 生产要素的国际流动研究

6. 跨国公司研究

7. 经济发展研究

8. 开放经济的宏观调控研究

9. 经济全球化与国际经济秩序研究

* 国际贸易纯理论

** 绝对利益学说

*** 绝对利益学说的基本内容

1. 绝对优势

   指在某种商品生产上，一国所耗费的劳动成本绝对低于其贸易伙伴国，那么
   劳动生产率就占绝对优势

2. 贸易方法

   各国从事占绝对优势的产品的生产，然后进行交换，那么双方都可以通过交
   换得到绝对利益，世界总体的福利水平也可以得到提高

*** 斯密绝对利益学说的数学说明

| 分工前 | X     | Y     | 分工后 | X   | Y   |
|--------+-------+-------+--------+-----+-----|
| A      | 1*1   | 2*0.5 | A      | 3*1 | 0   |
| B      | 2*0.5 | 1*1   | B      | 0   | 3*1 |

*表中数字第一个表示投入的劳动力，后一个表示单位劳动力的生产的产品数量*

对比分工前分工后可知：

1. 分工前AB两国共同投入6单位劳动力生产出了4单位的产品

2. 分工后AB两国仍然投入6单位劳动力生产出了6单位产品，世界总福利水平上升

*** 斯密绝对利益学说的图形解释

/参考大纲和教材/

*** 对斯密绝对利益学说的评价

1. 进步意义

   促进国际贸易的发展

2. 不足

   1. 只能解决发达国家与发达国家之间的贸易问题，但对于发展中国家和发达
      国家，或者发展中国家之间的贸易较难解释（有些国家没有绝对优势也进
      行国际贸易）

   2. 没有解释两种商品X、Y进行交换的内在等价要求是什么

** 李嘉图的比较利益学说

*** 比较利益（相对优势）学说的基本内容

假设前提：

1. 两个国家、两种商品、一种生产要素

2. 自由贸易，无贸易限制

3. 要素在国内自由流动，国家间不能流动

4. 生产成本不变，无规模收益

基本内容：

即使一个过家生产每种产品都处于绝对优势，而另一国家生产每种产品都处于绝
对劣势，只要它们的劳动生产率在不同产品存在差别，遵循“两利相权取其重，
两弊相衡取其轻”的原则，处于绝对优势的国家不必生产全部产品，而应该集中
生产本国国内具有最大优势的产品，处于绝对劣势的国家也不必停产所有的产品，
而只应该停止生产在本国国内处于最大劣势的产品，通过自由交换，双方便能从
国际分工和贸易种获得利益

*** 比较利益学说的简单数学说明

| 分工前 | X                      | Y                      | 分工后 | X            | Y                       |
|--------+------------------------+------------------------+--------+--------------+-------------------------|
| A      | $6 \times \frac{1}{6}$ | $4 \times \frac{1}{4}$ | A      | 0            | $10 \times \frac{1}{4}$ |
| B      | $1 \times 1$           | $2 \times \frac{1}{2}$ | B      | $3 \times 1$ | 0                       |

同绝对利益学说一样，可以发现

1. 分工前AB两国共同投入13单位劳动力生产出了4单位的产品

2. 分工后AB两国仍然投入13单位劳动力生产出了5.5单位产品，世界总福利水平
   上升

*** 比较利益学说的图形解释

/参考大纲或者教材/

*** 对比较利益学说的评价

1. 从国际贸易实际角度

   1. 进步之处

      揭示出了国际贸易因比较利益而发生并具有互利性，证明了各国出口相对
      成本较低而进口相对成本较高的产品可以实现贸易互利，进而可以发生国
      际贸易

   2. 不足之处

      1. 假设过于苛刻，不符合实际情况

      2. 按照学说，比较利益相差越大越容易发生贸易，当今的贸易便应该发
         生在发达国家和发展中国家之间，但实际情况是贸易主要发生在发达
         国家之间

      3. 按照学说，贸易会使得贸易参与过都获得好处，因此各国都应该积极
         参与，但现实是存在不同程度的贸易保护

2. 从劳动价值论角度

   1. 相对优势承认国内价值和国际价值的差异和交换比率不同，违背了李嘉图
      自己坚持劳动价值论

   2. 理论没有从根本上解释贸易发生的原因。李嘉图认为，比较利益（超额利
      润）是贸易产生的原因，但是即使不存在比较利益，只要能够实现商品的
      价值，贸易就会发生

   3. 比较利益学说暗含了一层意思：即越落后的国家参与国际贸易则越会从中
      受益。这实际上没有看到国际贸易具有的不等价交换和价值流向，难于被
      相对落后的国家所接受

3. 我国理论界对比较利益学说的认识和评价

   1. 20世纪50年代与苏联学者共同批判

   2. 20世纪60年代，评判吸收

   3. 改革开放以来，一分为二

*** 比较利益的分解

/参考大纲和教材的图形，注意约束线的斜率是价格的比，价格不表的福利提升
意味着分工带来的福利提升/

**** 来源贸易的利益

**** 来源分工的利益

**** 利益的合成分析与评价

** 国际贸易价格的确定

*** 相互需求方程式

比较交换AB两国国内XY交换与国际XY商品交换，确定两个可以交换的区间和国际
交换的均衡条件

|   |  X |  Y |
|---+----+----|
| A | 10 | 15 |
| B | 10 | 20 |

*表中数字代表单一劳动的各种商品产出*

表中可知

- A国的比较优势是生产X，国内的交换比率$10X = 15Y$

- B国的比较优势是生产Y，国内的交换比率$10X = 20Y$

所以

- 当国际市场的XY交换比率大于$10X:15Y$ 时A国会进入国际市场交换得到Y，反
  之会自己国内生产Y

- 当国际市场的XY交换比率小于$10X:20Y$ 时B国会进入国际市场交换得到X，反
  之会退出国际市场自己国内组织生产

- 实际国际市场的交换率在$10X:15F$ 和$10X:20F$ 之间，距离哪个国家的国内
  交换比率比较近，则得到的福利越少

*** 相互需求方程式的均衡条件

通国横置AB国国内X需求供给曲线图，可以确定世界市场上X的需求与供给

/详细参考大纲和教材/

*** 提供曲线

提供曲线由马歇尔和埃奇沃斯提出，它是相互需求曲线，表明一个国家为了进口
一定量的商品，必须向其他国家出口一定量的商品，因此提供曲线即对应某一进
口量意愿提供的出口量的轨迹。两个国家的提供曲线的交汇点所决定的价格，就
是国际商品交换价格

/这里书上有推导，详细参照教材/

*** 贸易条件

一般指单位出口能够换回的进口，即出口商品价格与进口商品价格的比率，简称
“交换比价”。一般用在一定时期（如一年）内的出口商品价格指数同进口商品价
格指数对比来表示。

贸易条件改善就是指与基期相比较而言，交换比价上升，即同等数量的出口商品
能够换回比基期更多的进口商品，反之称为贸易条件恶化。

*** 出口的贫困化增长

在一定条件下，一国生产规模的扩大，即生产可能性曲线向外推移，沿着原有优
势推进，即如果该国原有优势在于生产某种产品，现在进一步扩大该中产品的生
产，这种产品的相对价格下降，因此，贸易出口的扩大不仅没有使得该国的福利
有所提高，反而因为出口增加而有所下降。

这种现象的根源在与该国的贸易条件由于扩大出口而恶化。

出口的贫困化增长的条件：

1. 单一经济的发展中国家

2. 国际市场上的大国，出口商品为初级产品

3. 产品价格弹性小（价格的下降所带来的需求量的增量小）

4. 出口导向型经济，严重依赖出口

经济意义：

产业结构调整，平衡出口量和出口价格

* 国际贸易的现代与当代理论

** H-O模型（要素禀赋理论）及其分析

基本假设（2 \times 2 \times 2）：

要素生产率相等且可以自由流动；一个国家资本丰富，一个国家劳动丰富

*** 基本命题分析

1. 在国际贸易体系中，一国出口自己相对丰富的要素生产的产品，进口自己相
   对稀缺的要素生产的产品

2. 如果两国生产要素比例不同，即使要素的生产率相同，也会产生生产成本差
   异，两国会发生贸易

3. 交换的结果是使得各国间要素的报酬差异趋于减小，出现要素价格趋于均等
   化趋势

4. 理论中存在雷布津斯基定理和斯托尔泼-萨缪尔森定理（ *这点大纲没有要
   求, 参考教材* ）

*** H-O模型基本内在逻辑关系

“靠山吃山，靠水吃水”

要素的自然禀赋$\implies$ 要素的相对富饶程度$\implies$ 要素的供给
$\implies$ 要素相对价格差$\implies$ 生产成本差异$\implies$ 商品价格差异
$\implies$ 贸易产生

*** H-O模型的评价

丰富了贸易理论，从实际优势出发决定贸易模式（产品结构、地理格局），从贸
易对经济的影响分析贸易的作用，具有积极效果。不足之处在于从静态出发，没
有考虑动态效果及广泛性。

** 列昂惕夫反论及国际贸易新要素理论

*** 列昂惕夫反论

**** 内容

列昂惕夫对美国20世纪40年代和50年代的对外贸易情况进行了分析，发现美国参
加国际分工是建立在劳动密集型专业分工基础之上的，即出口劳动密集型商品，
进口资本密集型商品，通过对外贸易安排剩余劳动力和节约资本，这一结果与
H-O理论恰恰相反。

**** 解释

1. 列昂惕夫的解释（有效劳动理论）

   由于劳动素质各国不同，在同样的资本配合下，美国的劳动生产力约为他国
   （比如意大利）的3倍，因此若以他国作为衡量标准，则美国的有效劳动数量
   应该是现存劳动量的3倍。从有效劳动数量看，美国应为（有效）劳动相对丰
   富的国家，而资本在美国则成为相对稀缺的要素。

2. 要素密度逆转解释

   在某些国家中，X是资本密集型的，Y是劳动密集型的，但在一些国家，X变成
   劳动密集型，Y变成资本密集型。

*** 国际贸易新要素理论

**** 人力资本说

所谓人力资本是资本与劳动力结合而形成的一种新的生产要素，人们通过对劳动
力进行投资（教育、职业培训、保健等），可以提高原有劳动力的素质和技能，
劳动生产率得到提升，从而对一个国家参加国际分工的比较优势产生作用与影响。

该学说认为，人力资本结构与物质资本结构同样重要，一个国家应重视人力投资，
取得好的投资效益，才能产生新的比较优势。

**** R&D学说

研究与开发也是一种影响国际贸易格局的生产要素。研究是指新产品紧密相关联
的思路、技术、工艺方面的基础研究与应用研究；开发是指新产品的设计与试制，
即新产品的开发和创造。

在实际中，人们主要是通过考察衡量一个国家开发经费占产品销售总额的比重，
来间接考察一个国家的研究与开发水平。

强调了科技发展在国际贸易优势形成中的作用，符合目前社会向前发展的趋势。

**** 信息贸易理论

信息是一种可以创造价值并能进行交换的一种无形资源，是现代生产要素的组成
部分。信息是生产中的软件，是比较优势的软要素，它本身是可以交换的产品，
是一种可以做交换对象的软件要素，具有相应的价格。不同国家占有信息的多寡，
会使得他们在国家贸易中的比较优势发生变化，影响国际贸易的价格。

*** 国际贸易产品生命周期理论

**** 技术差距理论

不同国家因技术创新、技术模仿而存在的技术方面的时间和空间上的差异是解释
某类贸易发生的原因。由于科技市场资金人才等方面的差距，新产品一般先在发
达国家产生，其他国家由于技术差距，要等一段时间才能进行模仿生产，这段时
间便是贸易机会与可能性。

/图表参考大纲/

1. $T_0-T_1$ ：需求滞后，取决于收入因素、模仿国消费者对新产品的认识

2. $T_0-T_2$ ：反应滞后，取决于模仿国厂商的反应，以及规模经济、价格、
   市场、关税等

3. $T_2-T_3$ ：掌握滞后，取决于模仿国取得技术的渠道、消化技术的能力

4. $T_0-T_3$ ：模仿滞后之后，模仿国以低成本为基础出口

5. $T_1-T_3$ ：两国贸易期间

**** 产品的生命周期理论

***** 基本内容

1. 第一阶段，产品创新阶段
   
2. 第二阶段，外国开始模仿生产该产品的阶段，创新国产品在该国的竞争力下降

3. 第三阶段，外国模仿国以低成本为基础开始向第三国出口的阶段。创新国出
   口受到影响。

4. 第四阶段，外国产品进入创新市场，创新国开始从出口国转变为进口。

***** 图形说明

/参考大纲或者教材/

** 国际贸易的当代理论

*** 产业内贸易理论

**** 产品的同质性与异质性

- 产品同质性指产品间可以完全相互替代，市场区位不同，市场时间不同，但是
  商品需求的交叉弹性极高，且消费者对这类产品的消费偏好完全相同

- 产品异质性指产品相似但不完全相同，存在一定的差异，产品彼此之间不能完
  全替代但尚可进行一定程度的替代，交叉弹性小于同质产品，在生产中要素投
  入具有相似性

**** 同质产品的产业内贸易

- 不同国家间大宗产品的交叉型产业内贸易

- 经济合作或因经济技术因素而产生产业内贸易

- 大宗商品的转口贸易

- 政府干预产生的价格扭曲

- 季节性产品贸易

- 跨国公司的内部贸易也会形成产业内贸易

**** 异质产品的产业内贸易

产品在品牌、规格和服务上等特点上的不同，需求因特点不同产生既进口又出口
的现象

**** 需求偏好相似论

国际贸易可以看成是一国国内贸易跨越国界的延伸。实践中，厂商首先满足国内
熟悉的市场，人均收入决定一个国家的需求结构，收入相似则市场之间的隔阂较
小，易于发生贸易

**** 规模经济的贸易利益（规模经济贸易理论）

企业的长期平均成本随着产量增加而下降，企业面对的是市场需求曲线，市场需
求量会随着价格下跌而增加。在参与国际贸易之前，企业所面向的只是国内的需
求。由于国内市场需求有限，企业不能生产太多，从而使生产成本和产品价格不
得不保持在较高的水平上。如果企业参与国际贸易，产品所面临的市场就会扩大，
国内需求加上国外需求，企业生产就可以增加。由于生产处于规模经济阶段，产
量的增加反而使产品的平均成本降低，从而在国际市场上增加了竞争能力。规模
经济效应使资源禀赋即使无差异的国家之间也能凭生产规模大的优势形成竞争力，
取得贸易利益。

**** 产业内贸易水平的衡量指数

- 巴萨特指数

  $A_j = \frac{|X_j - M_j|}{X_j + M_j}$

- 格鲁贝尔-劳埃德指数（G-L指数）

  $B_j = 1 - A_j \times 100$

**** 对产业内贸易理论的评价

- 对传统贸易理论的批判，假设更符合实际情况，扩大了探讨的内容

- 从需求角度出发对国际贸易进行了考察

- 规模经济是当代经济重要的内容，对与它的追求，产生了许多利益

- 是对比较利益的补充和发展，但是基本是静态分析

*** 政策贸易理论

**** 战略政策理论

国家通过各种政策干预（税收、补贴等），在对本国至关重要的生产领域中创造
出比较优势，而这些生产领域具有很强的各种前后向联系，不仅可以带动经济发
展，而且具有广泛的外部经济效益，进而获得贸易收益，促进经济增长与发展。
因此一国政府在不完全竞争和规模经济条件下，可以凭借生产补贴、出口补贴或
保护国内市场等政策手段，扶持本国战略性工业的成长，增强其在国际市场上的
竞争能力，促使国际贸易的发生。

**** 贸易扭曲理论

政府通过政策干预，实施贸易保护政策，在边际进口替代率、产品边际转换率、
消费的边际替代率和边际技术替代率之间制造不相等，进而是的边际成本不等于
价格，出现贸易扭曲，让贸易畸形发展。

* 国际贸易政策分析

** 关税分析

*** 关税概念

是进出口商品在经过一个国家的关境时，由海关代表国家向进出口商品征收的一
种税赋。

*** 小国进口关税的局部均衡分析

/和微观经济学中征税的效应分析相近，参考大纲或者教材/

1. 保护效应
   
2. 消费效应

3. 贸易效应

4. 税收效应

5. 国际收支效应

*** 小国进口关税一般均衡分析

** 非关税壁垒分析

*** 进口配额

**** 概念

指一国政府在一定时期内，对与某些商品的进口数量或金额加以直接的限制

**** 经济效应

国内需求增加，进口配额不变，结果使该种商品价格上升，生产和消费都增加，
但是进口数量不变

*** 进口配额与等额关税的政策含义比较

1. 政策含义比较：
   
   1. 进口配额下，需求变动，国内的价格升高，国内生产增加；等额关税时，国
      内价格不变，生产不变，消费与进口要增加

   2. 进口配额下，许可证可以拍卖或者无偿分配，导致寻租行为

   3. 进口配额的进口数量是确定的，而进口关税的结果则因供求曲线的弹性不明
      而无法掌握

2. 进口配额的评价

   进口配额因数量明确而对国际贸易限制清楚，限制更强，国内厂商更愿意采
   用，对自由贸易的限制、危害更大

*** 反倾销与反补贴分析

**** 倾销的界定

- 倾销的定义

  倾销是一种商品在不同市场之间的价格歧视，是海外商品以低于同样商品在同
  一时间在国内市场类似条件下的销售价格出售

- 构成倾销的条件

  1. 产品以低于正常价值或公平价值的价格销售

  2. 低价销售的行为对进口国产业造成实质性的损害

  3. 损害与价格之间存在因果关系

**** 倾销的危害

1. 对出口国的影响

   1. 基站出口国其他企业的海外市场份额

   2. 损害出口国消费者的利益

   3. 扰乱出口国市场秩序

2. 对进口国影响

   1. 阻碍进口国相应产业的发展

   2. 扭曲进口国市场秩序

   3. 威胁和抑制进口国产业结构调整和新兴产业的建立

3. 对第三国的影响

   导致进口国对第三国产品的市场需求下降，使第三国在进口国的市场份额和
   利润减少

**** 无政府补贴的长期性倾销的条件

1. 出口国的企业具有一定的垄断能力

2. 国内外市场的弹性差异

3. 出口国对国外商品设置足够高的贸易壁垒

**** 反倾销的措施

1. 反倾销税

2. 出口商承诺（负面清单）

** 幼稚产业保护

*** 幼稚产业保护的理论基础

1. 李斯特的贸易保护理论

   建立在生产力论的基础上，认为生产财富的能力比财富本身，农业、原材料、
   科技可以自由贸易，但是工业必须得到保护，以获取未来的贸易利益，应该
   建立起保护性的关税制度。

2. 新贸易保护理论

   该学派认为，贸易利益在旧的国际经济秩序下是发达国家攫取发展中国家财
   富的渠道，即财富向发达国家转移，从外围向中心国家转移，科技利益均为
   发达国家获得，财富在发达国家聚集，而贫困则在发展中国家聚集。因此发
   展中国家应该实施贸易保护，切断不等价交换的价值渠道。

*** 幼稚产业的定义（M-B-K标准）

- 穆勒标准（产业自理原则）

  某种产业由于技术不足，生产率低下哦，成本高于国际市场，无法竞争，在保
  护下，能够在自由贸易下获利，自我投资发展，即为幼稚产业。

- 巴斯塔布尔标准（成本收益原则）

  保护、扶植幼稚行业所需要的社会成本不超过该产业将来利润的现值总和，符
  合条件即为幼稚产业。

- 肯普标准（外部性原则）

  如果某种技术可以为其他产业所获得，即使本产业利润无法增加，将来利润无
  法补偿投资成本，国家也应该予以保护。

*** 关税有效保护率的计算

关税的保护分为名义保护和有效保护，名义保护率即为名义税率；而有效保护则
是指对与受保护行业的单位产品附加价值增加率的保护

$EPR = \frac{V' - V}{V}$

$V'$ 为附加价值（最终产品价格-原料价格）

$V$ 为新加入的价值

*** 关税有效保护的政策含义与评价

1. 最终产品名义税率不变时，对进口原材料关税征收越低，该名义税率的保护
   作用也越大。

2. 如果用进口原料做加工出口，对原材料征税，将降低产品竞争力（政策上因
   此需要出口退税）。

3. 发展中国家的两难：若对原材料不征税，对最终产品征税，形成国内市场高
   保护，国内会出现大量的装配线，用组装占领市场，导致中间产业发展不足；
   如果对原材料征税，则产品无竞争力，无法与进口产品竞争，也无法转换称
   出口型产业。

* 国际收支分析

** 国际收支与国际收支表

*** 国际收支

- 广义国际收支

  在特定时期（通常是一年）内，一个经济体与世界其他地方的各项经济交易。
  大部分交易是在居民和非居民之间进行的。

- 狭义国际收支

  指一国在一定时期，同其他国家由于贸易、劳务、资本等往来而引起的资产转
  移，其特点是仅计入现在或者将来有外汇收支的项目。

*** 国际收支表的构成

- 经常账户（贸易、劳务）

  | 项目     | 内容                                                                                                                                   |
  |----------+----------------------------------------------------------------------------------------------------------------------------------------|
  | 货物     | 一般货物、用于加工的货物、货物修理、各种运输工具的采购、非货币黄金                                                                     |
  | 服务     | 运输、旅游、通信、建筑、保险、金融、计算机、专有权使用费、个人娱乐、文化服务和别处未提及的政府服务                                     |
  | 收入     | 职工报酬、投资收入（直接、间接投资）                                                                                                   |
  | 经常转移 | 除了固定资产所有权的转移、与固定资产联系的收买或放弃为条件的资金转移、债权人不要回报的债务取消这三项之外的其他转移，例如保险费、侨汇等 |

- 资本和金融账户

  | 项目     | 内容                                                                                                                                                                                                            |
  |----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
  | 资本账户 | 资本转移（各级政府和其他转移，如债务减免）、非生产、非金融资产的收购、放弃（各种无形资产，如可转让的合同及商誉等）                                                                                              |
  | 金融账户 | 直接投资、证劵投资、其他投资、储备资产（货币化黄金、SDR、外汇资产、在基金组织中的头寸等）、金融补充信息，包括构成外国当局储备的负债（欠国外的债务证劵、存款等）和特殊融资交易（国际赠款、债务减免和央行借款等） |

- 国际头寸

  不属于国际收支表的标准组成，它与国际收支表构成一国全面的国际账户，是
  一国对外金融资产和负债存量的平衡，其构成为资产、负债，项目与国际收支
  的金融账户一致。

  /国际收支表反应流量情况，国际头寸反应存量情况/

** 国际收支的调节

*** 国际收支的失衡

指经常账户、金融与资本账户的余额出现问题，即对外经济出现了需要调整的情
况

影响：

- 对外，造成汇率、资源配置、福利提高的困难

- 对内，造成经济增长与经济发展困难

*** 国际收支失衡调节理论

**** 弹性调节法

- 调节机制

  - 贸易逆差$\implies$ 本币对外贬值$\implies$ 本国出口价格下降（进口价
    格上升）$\implies$ 出口量上升（进口量下降）$\implies$ 国际收支改善

  - 贸易顺差$\implies$ 本币对外升值$\implies$ 本国出口价格上升（进口价
    格下降）$\implies$ 出口量下降（进口量上升）$\implies$ 国际收支改善

- 发挥作用的条件

  - 贸易对手国对于上述流程这样的结果表示接受

  - 本币的对外贬值速度快于对内贬值

  - 出口商品的变化对于价格调整的反应程度要大（弹性之和大于1），符合马
    歇尔-勒纳条件

- J曲线效应

  本币贬值先造成收支的继续恶化，然后才会好转。因为出口增长有时滞

**** 吸收法

宏观经济分析方法(总需求管理）

\begin{cases}
Y = C + I + G + (X - M) \\
BOP = X - M \\
A = C + I + G \\
BOP = Y - A \\
\end{cases}

**** 货币法

通过调整国内货币供给调节国内需求，进而调整国际收支的变动。即国内货币供
给是国际储备与国内信贷之和，于是国际储备的变动是国内货币供给减去国内信
贷额的结果。如果信贷额的发行大于货币供给的需要，国际收支就会恶化，反之
则改善。

调节手段：

控制信贷发行和出售储备资产

* 汇率决定的一般理论

** 外汇及汇率

*** 外汇的定义及其作用

**** 外汇的概念

一国货币当局保有的以银行存款、财政部库卷、长短期政府证劵等形式持有的可
以在国际收支出现逆差时进行支付的债券

**** 外汇的作用

1. 价值尺度

2. 国际购买手段

3. 国际支付手段

4. 国际储备手段

**** 最佳外汇储备规模

- 三个月进口支付水平

- 10%国内生产总值

- 外债余额的30%

*** 汇率定义与汇率的标价法

**** 定义

不同货币在外汇买卖过程中形成的交换比例

**** 汇率标价法

- 直接标价法（一单位外币换多少本币）

- 间接标价法（一单位本币换多少外币）

- 美元标价法

** 汇率决定的若干理论

*** 汇率决定的传统理论（二战前）

**** 铸币平价说

该学说认为两国货币的价值量之比表现为货币的法定含金量之比，它是汇率决定
的基础。在该制度下，实际汇率围绕平价浮动，只要黄金自由流动，对其不加限
制，不会出现银行卷超过黄金储备的过量发行，银行卷不会贬值，汇率将在黄金
输送点之间波动。

**** 国际借贷说

国际借贷的差额是决定汇率变动的基础，该差额是由经常项目与资本项目的差额
决定的。一国债权大于债务，国际市场对该国货币供不应求，汇率上升，反之下
降。

**** 传统购买力平价说

该学说是纸币本位的产物。分为绝对购买力平价和相对购买力平价两种。

***** 绝对购买力平价

汇率决定于两国一般物价水平比值。

$E_0 = \frac{\sum P_a}{\sum P_b}$

***** 相对购买力平价

当两个国家都存在通货膨胀时，名义汇率等于过去的汇率乘以两国通货膨胀的比
值。甲国发生通货膨胀，其货币购买力下降，若乙国物价不变，则甲国货币在乙
国的价值下降。

汇率决定于两国货币的购买力之比，购买力取决于通货膨胀，而通货膨胀取决于
货币数量，因而该学说的理论基础是货币数量论。

$E_t = E_0 \cdot \frac{I_a}{I_b}$

**** 汇兑心理说

人们主观上对外汇的平价不同（心理平价不同），造成外汇供求的变化，进而导
致汇率变动。实际中，人们的心里平价会受到外汇质和量两方面的影响：前者为
货币特定购买力、支付债务能力、制度性因素等；后者为国际收支、货币数量、
财政状况等，二者结合才能构成对于外汇完全的主观评价。如果外汇供给增加，
边际效用下降，心理评价降低，汇率下浮，货币价值下降。

*** 二战后汇率决定的理论

**** 流动资产选择说

/发展自国际借贷学说/

人们对于资产形式的选择，即资产替换和资本流动如果量大且过于频繁，有可能
引起资本的大规模流动，在短期甚至中期内对于国际收支的影响要远大于经常项
目，资本大量流出，国际收支逆差加大，汇率下浮。

**** 目标汇率说

国际收支平衡是一个国家的宏观经济目标之一，为了达到平衡，人们总是将汇率
变动作为一种政策手段，因此结合经济状况确定某一汇率，结合财政、金融的其
他手段来实现经济的最终目标，即汇率应该由经济目标来决定，人为进行干预是
必要的。

**** 货币主义的汇率理论

这一理论是从购买力平价的绝对平价发展而来，认为汇率于货币供给之间存在着
非常密切的关系，通货膨胀因素在汇率决定中具有重要的作用，进而国家货币发
行量最终决定汇率。该理论认为汇率应该是浮动的而不是固定的，汇率的稳定有
待世界通货膨胀的解决，而这又必须在各国共同努力下才能做到，因此，大国应
该对世界通货膨胀稳定性负责。

*** 一般理论（一价定律）

**** 一价定律

在有无数交易者的完全竞争市场上，相同的交易产品或金融资产，经过汇率调整
后。在世界范围内其交易成本一定相等。它主要由购买力平价、利息平价和远期
汇率等经济关系表现出来。

**** 利息平价于远期汇率的决定

***** 费舍效应

名义利率之差应该等于预期通货膨胀之差。

$R_{ht} - R_{ft} = I_{ht} - I_{ft}$

***** 国际费雪效应

将利率关系、通货膨胀于货币价值关系结合在一起考虑。一国相对于其他国家发
生通货膨胀，将会伴随该国货币价值下降，同时伴随该国名义利率相对于外国利
率提高。

***** 远期汇率和升贴水公式

假设当前拥有$Y$ 资产，国内利率为$R_h$ ，外国利率为$R_f$ ，当期两国汇率
为$E_0$ ，远期两国汇率为$E_t$

$Y$ 资产有两种投资方式，一种存国内，一种存国外，两种方式的到期收益为

国内：$Y \cdot (1 + R_h)$

国外：$Y \cdot E_0 \cdot (1 + R_f) \cdot \frac{1}{E_t}$

根据一价定律，两种投资获得的收益应该相等，所以有

$Y \cdot (1 + R_h) = Y \cdot E_0 \cdot (1 + R_f) \cdot \frac{1}{E_t}$

化简之后可的

远期汇率的公式：$E_t = E_0 \cdot \frac{1 + R_f}{1 + R_h}$

升贴水公式：$E_t - E_0 = E_0 \cdot \frac{R_f - R_h}{1 + R_h}$

因为$R_h$ 一般比较小，$1+R_h$ 约等于1，所以升贴水公式可以约简为:
$E_t - E_0 = E_0 \cdot (R_f - R_h)$

1. 升水$E_t - E_0 > 0$

2. 贴水$E_t - E_0 < 0$

3. 平价$E_t - E_0 = 0$

一般情况下，利息较高的货币远期汇率大多呈贴水，利息较低的货币远期汇率大
多呈升水，这被成为*利率平价理论*。

* 要素的国际流动

** 资本国际流动及其经济效应

*** 资本国际流动

1. 资本国际流动的动因：

   1. 不同国家间资本收益率的差异

   2. 汇率变动及国际收支不平衡

   3. 风险因素

   4. 其他因素

2. 资本国际流动的主要形式

   1. 国家资本的输出和私人资本的输出

   2. 长期资本的国际流动和短期资本的国际流动

   3. 直接投资和间接投资

*** 资本国际流动的经济分析

1. 资本国际流动的图形和福利分析

   /参考大纲或教材的图形解释/

*** 国际生产折衷理论（为什么产生FDI）

一个企业的所有权特定优势、内部化、区位特定优势三者结合决定了该企业与其
他企业相比较是否具有对外投资的优势，或者可以通过出口、技术转移来开拓优
势。所有权特定优势与市场内部化优势是跨国公司对外投资的必要条件，它们并
不能决定一个公司一定要通过直接投资参与国际经济活动，而工业区位优势则是
跨国公司进行对外投资的充分条件，二者结合决定了直接投资的发生。

- 所有权特定优势

  指企业具有的组织管理能力、金融融资方面的优势、技术方面的特点和优势、
  企业的规模与其垄断地位及其它能力，这些优势组成了企业比投资所在国公司
  更大的优势，可以克服在国外生产碰到的附加成本和制度风险。

- 内部化

  指将企业所有权特定优势内部化的能力。因为外部市场不完全，企业所有权特
  定优势可能会受到打击而丧失，内部化是在企业内部更好地实行资源配置，克
  服不利条件。

- 区位特定优势

  包括东道国的劳动力成本情况，市场的条件和需求状况、关税与非关税壁垒、
  东道国政府的各种政策等等

** 劳动力国际流动及其经济效应

*** 劳动力国际流动的原因

1. 国民收入的国际差异

2. 各国劳动力供求不平衡

3. 经济周期

4. 伴随国际贸易和国际投资及其他国际经济活动的劳动力流动

5. 劳动力日益具有跨国流动的必要条件

*** 劳动力国际流动的经济分析

/参考大纲或者教材的分析，和资本流动的分析完全一致/

** 技术转移及其经济效应

*** 技术的国际转移

**** 技术转移的动因

技术对于经济的促进作用和带个企业的经济利益，同时能够使得产业结构发生变
化，以及在国际市场中竞争力提高。

**** 技术转移的形式

技术转移属于软件的流动，形式包括专利使用、技术秘密的使用、制造技术的传
播、专有技术的转让等，具体有着垂直型、水平型、混合型，简单型、吸收型等。

1. 垂直型技术转移

   一国基础研究成果被另一国在应用研究中采用，或一国应用研究的成果被另
   一国家的生产所采用。

2. 水平型技术转移

   一国以应用的技术被另一国生产所采用。

3. 混合型技术转移

   一国技术转移同时存在垂直型与水平型的情况。

4. 简单型技术转移

   一国技术转移到另一国，不理会被转移国家能否复制出该技术。

5. 吸收型技术转移

   一国技术转移到另一国，被转移国家能够复制出该技术。

*** 国际技术转移的经济分析

**** 技术转移的新古典价格刺激模型

劳动资本可以相互转换，导致生产往生产成本小的组合方向移动。

**** 中性技术进步说

**** 技术转移的周期理论

产品出口、直接投资、技术输出

**** 国际技术转移的政策含义

** 国际要素转移的其他经济效应

*** 两缺口模型                                                   :2020重点:

**** 模型内容

总需求：$Y = C + S + T + M$

总供给：$AD = C + I + G + X$

总需求等于总供给，不考虑国内均衡，所以假设$G=T$ ，得到：$I - S = M -X$

$I-S$ 为储蓄缺口

$M-X$ 为进口缺口

**** 模型意义

模型强调了发展中国家利用外部资源的必要性。通过引入外部资源，可以提高一
国出口能力，是的高收入高储蓄的良性循环出现，更加合理地配置资源。在引进
外部资源时，国内的经济结构需要进行调整以适应引进外部资源的要求，同时应
该发挥政府在调控经济活动中的作用。

*** 外资引进的经济分析

**** 国内的恶性循环

发展中国家人均收入低$\implies$ 储蓄低$\implies$ 资本形成不足$\implies$
生产率低下，收入不高$\implies$ 低购买力$\implies$ 投资不足$\implies$
生产率低下$\implies$ 收入低下

从外部引进资源，注入到生产过程中是打破恶性循环的有效方法之一

**** 最佳外资引进分析

$MR = MC$

**** 债务指标及其政策意义

1. 偿债率

   当年还本付息额占出口总收入的比重，即每年出口收入中有多少被用于偿付
   到期的本息，应该小于20%。

2. 出口债务率

   当年外债余额与当前出口总额之比，表示所欠外债额与出口收入之间的关系，
   应该小于100%。

3. 经济债务率

   当年外债余额占当年国民生产总值的比重，表示所欠外债额与整体经济之间
   的关系。安全线为30%

4. 现值债务率（95年以后计算方法）

   未偿还债务现值占国民生产总值的比重，80%为临界值

5. 出口现值债务率（95年以后计算方法）

   未偿还债务现值与出口之比，20%临界值，大于60%为中等债务国家

* 宏观经济的内外均衡

** 国际传导机制（非均衡传导）

1. 国际商品流动的非均衡传导机制

2. 国际资本流动的非均衡传导机制

3. 国际劳动力流动的非均衡传导机制

4. 国际信息流动的非均衡传导机制

** 贸易乘数

* 经济一体化与国际经济秩序分析

** 经济一体化分析

*** 关税同盟

1. 含义

   是经济一体化的组成形式之一，关税同盟从欧洲开始。对内实行减免关税，
   商品自由流动，从而成员国居民可以享受比过去更低成本的商品消费，同时
   增加了可选择机会，因此成员国乃至关税同盟整体的经济福利会提高；对外
   则采取统一或逐步实行统一的对外关税和对外贸易政策。关税同盟有两种经
   济效应，即静态效应和动态效应，静态效应有贸易创造效应和贸易转移效应
   两种。各国之间结成贸易联盟在一定程度上比自由贸易更能提高成员国的福
   利水平。

2. 关税同盟的经济效应

   1. 贸易创造效应

      指产品从生产成本较高的国内生产转向较低成本的关税同盟中贸易对象国
      生产，本国从贸易对象国进口的一种过程和现象。对发展有积极的促进意
      义。

   2. 贸易转移效应

      指产品从过去进口自较低生产成本国转向从较高成本国进口的过程和现象。
      是在一体化过程中应该注意的情况。

   3. 当贸易创造效应大于转移效应是，参加关税同盟给成员国带来的综合效应
      就是净效应，意味着成员国经济福利水平提高；反之，则为净损失和经济
      福利水平下降。

3. 关税同盟的政策含义

   1. 关税同盟成员国与外部世界国家生产成本相差小则利益大

   2. 结成关税同盟前，成员间关税高，则结成后同盟利益大

   3. 同盟成员与非成员之间的贸易壁垒低，则贸易创造多

   4. 关税同盟成员数目越多，则低成本成员国存在的可能性大，进而贸易创造
      的机会多

   5. 关税同盟成员家的竞争性大于互补性，则结成关税同盟的利益大

*** 最优货币区理论

1. 基本概念

   指采用单一货币，或者几种货币之间汇率永久固定、对外统一浮动的经济区
   域。

2. 形成条件

   1. 价格与工资弹性

   2. 要素市场融合

   3. 金融市场融合

   4. 商品市场高度融合

   5. 宏观经济协调与政治融合

3. 单一货币的收益

   1. 消除交易成本

   2. 消除汇率不确定性

   3. 形成更稳健的价格机制和降低实际利率水平

   4. 信用延伸收益

   5. 稳健的政府财政

      1. 稳健自律的重要性

         如果过度赤字，则债务货币化或着政府破产

      2. 欧盟有关财政约束的实践（《马约》）

         1. 欧盟成员国在加入欧元区前一年财政赤字不得超过当年GDP的3%

         2. 公债占GDP的比重不得超过60%

4. 单一货币的成本

   1. 缺乏需求变化的调节手段

   2. 改变国内非均衡偏好的成本

   3. 劳动力市场结构差异造成的成本

   4. 单一货币下财政体制不同的成本

   5. 国家间经济增长率不同导致贸易不平衡

* 经济全球化趋势

